# Generated by Django 2.1.5 on 2019-01-16 00:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
