# Generated by Django 2.1.5 on 2019-01-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190116_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='correct_questions_ids',
        ),
        migrations.AlterField(
            model_name='sitting',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz the user is taking', on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='score',
            field=models.IntegerField(blank=True, default=0, help_text="The user's quiz score."),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_choices',
            field=models.ManyToManyField(blank=True, help_text="The user's submitted answers", to='quiz.Choice', verbose_name='Choices'),
        ),
    ]
